### ISSUE TITLE
Is card game war being played right?

### ISSUE THREAD

**Issue by bneil** [bsamaripa/Wonderland-Scala-Katas#3]
Its weird that you would give out two 52 card decks since that could possibly lead to two cards having an identical rank and suite. Usually when I played it as a kid it was a single deck split between the players. Ive updated on my fork but wanted to bring it to your attention :+1:

**Comment by bsamaripa** [comment]
My thinking was that the deck was meant to be divided into two half decks but generate only the single deck. Do you think that I should split the deck up to two new ones upon creation?

**Comment by bneil** [comment]
imho you should take a single 52 card deck and split it in half, giving one half to player 1 and the other to player 2. Take a look at my implementation: https://github.com/bneil/Wonderland-Scala-Katas/blob/master/CardGameWar/src/main/scala/CardGameWar.scala#L79

**Comment by bsamaripa** [comment]
Makes sense to me and your implementation looks pretty solid. I would go ahead and make a pull request for the implementation to be modified.

**Comment by bsamaripa** [comment]
Implemented your suggestion for two decks. Thanks @bneil
